import { logger } from '../../utils/logger.js';
import { llmClient } from './llmClient.js';

export const reflectionStep = {
    /**
     * Reflects on and audits the generated response before returning it to the user.
     * @param {string} userQuery - The original user message.
     * @param {string} generatedText - The response generated by responseGenerator.
     * @param {Object} plan - The plan created by agentPlanner.
     * @param {Object} keys - API keys.
     * @returns {Object} Reflection audit result: { did_i_answer: boolean, missing_info: [], confidence: number, text: string }
     */
    async reflect(userQuery, generatedText, plan, keys = {}) {
        logger.info(`[REFLECTION] Reflecting on generated answer quality...`, 'AI_REFLECTION');

        const geminiKey = keys.geminiKey || process.env.GEMINI_API_KEY || (process.env.AI_API_KEY?.startsWith('AIzaSy') ? process.env.AI_API_KEY : null);
        const groqKey = keys.groqKey || process.env.GROQ_API_KEY || null;

        let did_i_answer = true;
        let missing_info = [];
        let confidence = 0.90;
        let adjustedText = generatedText;

        // LLM Reflection (if key is active)
        if (geminiKey || groqKey) {
            try {
                const prompt = `You are an AI answer quality inspector.
Reflect on the generated response and verify if it correctly and fully answers the user query.
Determine:
1. did_i_answer: (boolean) Did the text answer the user query? (Set false if it contains placeholders, errors, or fails to address the user's core intent).
2. missing_info: (array of strings) Any critical parameters/questions that were not addressed.
3. confidence: (number, 0.0 to 1.0) Overall answer completeness and correctness confidence.

USER QUERY: "${userQuery}"
GENERATED RESPONSE: "${generatedText}"
REQUIRED PARAMETERS: "${plan.information_needed.join(', ')}"

Return a JSON object:
{
  "did_i_answer": boolean,
  "missing_info": [string],
  "confidence": number
}
Return ONLY valid JSON.`;

                const text = await llmClient.query({
                    prompt,
                    jsonMode: true,
                    keys
                });

                if (text) {
                    const parsed = JSON.parse(text);
                    did_i_answer = parsed.did_i_answer;
                    missing_info = parsed.missing_info || [];
                    confidence = parsed.confidence || 0.8;

                    logger.info(`[REFLECTION] LLM Audit: did_i_answer=${did_i_answer}, confidence=${confidence}`, 'AI_REFLECTION');
                }
            } catch (err) {
                logger.error(`[REFLECTION] LLM reflection failed: ${err.message}`, 'AI_REFLECTION');
            }
        } else {
            // Local fallback rules
            if (generatedText.includes('offline fallback') || generatedText.includes('degraded') || generatedText.includes('unreachable')) {
                confidence = 0.65;
            }
            if (plan.missing_information && plan.missing_information.length > 0) {
                did_i_answer = false;
                missing_info = plan.missing_information;
                confidence = 0.5;
            }
        }

        // Adjust text if quality check fails or confidence is too low
        if (confidence < 0.70 || !did_i_answer) {
            logger.warn(`[REFLECTION] Low confidence alert (${confidence}). Adjusting output with helpful clarifying request...`, 'AI_REFLECTION');
            
            // Append a friendly follow-up query if not already present
            if (!generatedText.includes('skin type') && !generatedText.includes('budget')) {
                adjustedText = `${generatedText}\n\n*To help me provide a more accurate recommendation, could you tell me your skin type (oily, dry, sensitive), primary concern, or maximum budget?*`;
            }
        }

        return {
            did_i_answer,
            missing_info,
            confidence,
            text: adjustedText
        };
    }
};
